/*
 * JS for HomeScreen generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '65801e8a-6228-4ec2-a5cb-baad9e97f627';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "how_to_play",
    "location": "how_to_play.html"
}, {
    "name": "settings",
    "location": "settings.html"
}, {
    "name": "HomeScreen",
    "location": "HomeScreen.html"
}];

function HomeScreen_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage_2': 'HomeScreen_mobileimage_2',
        'mobilebutton_9': 'HomeScreen_mobilebutton_9',
        'settings_page': 'HomeScreen_settings_page'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'HomeScreen';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var HomeScreen_onLoad = function() {
        HomeScreen_elementsExtraJS();
        HomeScreen_deviceEvents();
        HomeScreen_windowEvents();
        HomeScreen_elementsEvents();
    };
    // screen window events
    function HomeScreen_windowEvents() {
        $('#HomeScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function HomeScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function HomeScreen_elementsExtraJS() {
        // screen (HomeScreen) extra code
    };
    // screen elements handler
    function HomeScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#HomeScreen_mobilecontainer [name="mobilebutton_9"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('startScreen', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#HomeScreen_mobilecontainer [name="mobilebutton_9"]');
        $(document).off("click", '#HomeScreen_mobilecontainer [name="settings_page"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('settings', {
                        transition: 'pop',
                        reverse: false
                    });
                }
            },
        }, '#HomeScreen_mobilecontainer [name="settings_page"]');
    };
    $(document).off("pagebeforeshow", "#HomeScreen").on("pagebeforeshow", "#HomeScreen", function(event, ui) {
        Apperyio.CurrentScreen = "HomeScreen";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    HomeScreen_onLoad();
};
$(document).off("pagecreate", "#HomeScreen").on("pagecreate", "#HomeScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    HomeScreen_js();
});