/*
 * JS for how_to_play generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '65801e8a-6228-4ec2-a5cb-baad9e97f627';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "how_to_play",
    "location": "how_to_play.html"
}, {
    "name": "settings",
    "location": "settings.html"
}, {
    "name": "HomeScreen",
    "location": "HomeScreen.html"
}];

function how_to_play_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobiletextarea_2': 'how_to_play_mobiletextarea_2'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.datasources = Apperyio.datasources || {};
    Apperyio.CurrentScreen = 'how_to_play';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var how_to_play_onLoad = function() {
        how_to_play_elementsExtraJS();
        how_to_play_deviceEvents();
        how_to_play_windowEvents();
        how_to_play_elementsEvents();
    };
    // screen window events
    function how_to_play_windowEvents() {
        $('#how_to_play').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function how_to_play_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function how_to_play_elementsExtraJS() {
        // screen (how_to_play) extra code
    };
    // screen elements handler
    function how_to_play_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
    };
    $(document).off("pagebeforeshow", "#how_to_play").on("pagebeforeshow", "#how_to_play", function(event, ui) {
        Apperyio.CurrentScreen = "how_to_play";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    how_to_play_onLoad();
};
$(document).off("pagecreate", "#how_to_play").on("pagecreate", "#how_to_play", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    how_to_play_js();
});