/*
 * JS for startScreen generated by Appery.io
 */
Apperyio.getProjectGUID = function() {
    return '65801e8a-6228-4ec2-a5cb-baad9e97f627';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}
Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "how_to_play",
    "location": "how_to_play.html"
}, {
    "name": "settings",
    "location": "settings.html"
}, {
    "name": "HomeScreen",
    "location": "HomeScreen.html"
}];

function startScreen_js() {
    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_2': 'startScreen_mobilebutton_2',
        'mobiletextinput_3': 'startScreen_mobiletextinput_3',
        'mobiletextinput_4': 'startScreen_mobiletextinput_4',
        'googlemap_5': 'startScreen_googlemap_5',
        'marker_6': 'startScreen_marker_6',
        'mobilebutton_7': 'startScreen_mobilebutton_7'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    /*
     * Nonvisual components
     */
    Apperyio.mappings = Apperyio.mappings || {};
    Apperyio.mappings["startScreen_geolocation1_onsuccess_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "from_name": "geolocation1",
                "from_type": "SERVICE_RESPONSE",
                "to_name": "startScreen",
                "to_type": "UI",
                "mappings": [
                    {
                        "source": "$['data']['coords']['latitude']",
                        "target": "$['mobiletextinput_3:text']"
                    },
                    {
                        "source": "$['data']['coords']['longitude']",
                        "target": "$['mobiletextinput_4:text']"
                    },
                    {
                        "source": "$['data']['coords']['latitude']",
                        "target": "$['googlemap_5:latitude']"
                    },
                    {
                        "source": "$['data']['coords']['longitude']",
                        "target": "$['googlemap_5:longitude']"
                    }
                ]
            }
        ]
    };
    Apperyio.mappings["startScreen_geolocation1_onbeforesend_mapping_0"] = {
        "homeScreen": "startScreen",
        "directions": [
            {
                "to_name": "geolocation1",
                "to_type": "SERVICE_REQUEST",
                "to_default": {
                    "data": {
                        "options": {
                            "maximumAge": 3000,
                            "timeout": 5000,
                            "enableHighAccuracy": true,
                            "watchPosition": false
                        }
                    }
                },
                "mappings": []
            }
        ]
    };
    Apperyio.datasources = Apperyio.datasources || {};
    window.geolocation1 = Apperyio.datasources.geolocation1 = new Apperyio.DataSource(GeolocationService, {
        "onBeforeSend": function(jqXHR) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_geolocation1_onbeforesend_mapping_0"]);
        },
        "onComplete": function(jqXHR, textStatus) {
        },
        "onSuccess": function(data) {
            Apperyio.processMappingAction(Apperyio.mappings["startScreen_geolocation1_onsuccess_mapping_0"]);
        },
        "onError": function(jqXHR, textStatus, errorThrown) {}
    });
    Apperyio.CurrentScreen = 'startScreen';
    _.chain(Apperyio.mappings)
        .filter(function(m) {
            return m.homeScreen === Apperyio.CurrentScreen;
        })
        .each(Apperyio.UIHandler.hideTemplateComponents);
    /*
     * Events and handlers
     */
    // On Load
    var startScreen_onLoad = function() {
        startScreen_elementsExtraJS();
        startScreen_deviceEvents();
        startScreen_windowEvents();
        startScreen_elementsEvents();
    };
    // screen window events
    function startScreen_windowEvents() {
        $('#startScreen').bind('pageshow orientationchange', function() {
            var _page = this;
            adjustContentHeightWithPadding(_page);
        });
    };
    // device events
    function startScreen_deviceEvents() {
        document.addEventListener("deviceready", function() {
        });
    };
    // screen elements extra js
    function startScreen_elementsExtraJS() {
        // screen (startScreen) extra code
        /* googlemap_5 */
        $("[name = 'googlemap_5']").wrap("<div/>");
        $("[name = 'googlemap_5']").parent().css("margin-left", $("[name = 'googlemap_5']").css("margin-left"));
        $("[name = 'googlemap_5']").parent().css("margin-right", $("[name = 'googlemap_5']").css("margin-right"));
        $("[name = 'googlemap_5']").css("margin-left", '0');
        $("[name = 'googlemap_5']").css("margin-right", '0');
        var googlemap_5_options = {
            markerSourceName: "googlemap_5_markers",
            latitude: "",
            longitude: "",
            address: "San Francisco, CA",
            zoom: 10,
            showLocationMarker: false
        }
        Apperyio.__registerComponent('googlemap_5', new Apperyio.ApperyMapComponent("googlemap_5", googlemap_5_options));
        $("[name='googlemap_5_markers'] [apperytype='marker']").attr("reRender", "googlemap_5");

        function __update_googlemap_5(event, ui) {
            if (($('#startScreen_googlemap_5', ui.toPage).length > 0) && (Apperyio('googlemap_5') != undefined) && (Apperyio('googlemap_5').isInitialized)) {
                Apperyio('googlemap_5').refresh();
            }
        }
        $(":mobile-pagecontainer").off("pagecontainershow.startScreen_mobilecontainer", __update_googlemap_5).on("pagecontainershow.startScreen_mobilecontainer", __update_googlemap_5);
    };
    // screen elements handler
    function startScreen_elementsEvents() {
        $(document).on("click", "a :input,a a,a fieldset label", function(event) {
            event.stopPropagation();
        });
        $(document).off("click", '#startScreen_mobileheader [name="mobilebutton_2"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    try {
                        geolocation1.execute({});
                    } catch (e) {
                        console.error(e);
                        hideSpinner();
                    };
                }
            },
        }, '#startScreen_mobileheader [name="mobilebutton_2"]');
        $(document).off("click", '#startScreen_mobilecontainer [name="mobilebutton_7"]').on({
            click: function(event) {
                if (!$(this).attr('disabled')) {
                    Apperyio.navigateTo('HomeScreen', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        }, '#startScreen_mobilecontainer [name="mobilebutton_7"]');
    };
    $(document).off("pagebeforeshow", "#startScreen").on("pagebeforeshow", "#startScreen", function(event, ui) {
        Apperyio.CurrentScreen = "startScreen";
        _.chain(Apperyio.mappings)
            .filter(function(m) {
                return m.homeScreen === Apperyio.CurrentScreen;
            })
            .each(Apperyio.UIHandler.hideTemplateComponents);
    });
    startScreen_onLoad();
};
$(document).off("pagecreate", "#startScreen").on("pagecreate", "#startScreen", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    startScreen_js();
});